<main class="container_body">

    <section class="main">
    	<h1>Sport</h1>
		<img src="assets/images/turismo.jpeg" alt="automobile" class="main-img">
		<p>Lorem ipsum dolor sit amet</p>
	</section>
	
	<section class="main">
		<h1>Sport</h1>
		<img src="assets/images/turismo.jpeg" alt="automobile" class="main-img">
		<h1>automobile 2021</h1>
		<p>Lorem ipsum dolor sit amet</p>
	</section>
	
	<section class="main">
		<img src="assets/images/turismo.jpeg" alt="automobile" class="main-img">
		<h1>automobile 2021</h1>
		<p>Lorem ipsum dolor sit amet</p>
	</section>
    
   
</main>
