<main>
	
	<h3>Ajouter un esport</h3>
    
	<form method="post" enctype="multipart/form-data"> <!--action="article.phtml-->

		<p>
		    <label for='name'>Nom du esport</label>
		    <input type="text" name="name" id="name"/>
		</p>
		<p>
		    <label for='description'>Description</label>
		    <input type="text" name="description" id="description"/>
		</p>
		<p>
		    <label for='date_debut'>Date de début</label>
		    <input type="date" name="date_debut" id="date_debut"/>
		</p>
		<p>
		    <label for='date_fin'>Date de fin</label>
		    <input type="date" name="date_fin" id="date_fin"/>
		</p>
		
		<p>
			<label for="img">Image</label>
			<input type="file" name="img" id="img"/>
		</p>
		<p>	
			<label for="alt">Alt</label>
			<input type="text" name="alt" id="alt"/>
		</p>

			<button type="submit">Enregistrer</button>
	</form>
	
</main>