<section>
 <h2>Players</h2>
    
    <table>
        <tr>
            <th>ID</th>
            <th>Esport</th>
            <th>Pays</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Age</th>
        </tr>
        
        <?php foreach($players as $player): ?>
        <tr>
            <td><?= $player['userId'] ?></td>
            <td><?= $player['esportName'] ?></td>
            <td><?= $player['paysName'] ?></td>
            <td><?= $player['firstname'] ?></td>
            <td><?= $player['lastname'] ?></td>
            <td><?= $player['email'] ?></td>
            <td><?= $player['age'] ?></td>            
        </tr>
        <?php endforeach; ?>
    </table>

</section>



