<main>
   <?php var_dump($_SESSION)?>
    <table>
            <tr>
            	<th>ID user</th>
                <th>Email</th>
                <th>Firstname</th>
                <th>Lastname</th>
                <th>Age</th>
                <th>Pays</th>
                <th>Esport</th>
            </tr>
         
            <?php foreach($users as $user): ?>
            <tr>
            	<td><?= $user['userId'] ?></td>
                <td><?= $user['userEmail'] ?></td>
                <td><?= $user['firstname'] ?></td>
                <td><?= $user['lastname'] ?></td>
                <td><?= $user['age'] ?></td>
                <td><?= $user['paysName'] ?></td>
                <td><?= $user['esportName'] ?></td>
            </tr>
            <?php endforeach; ?>
        </table> 
        
</main>
<script src="js/main.js"></script>