<main>
	<form method="post">
		<p>
			<label for='email'>Email</label>
			<input type="email" name="email" id="email">
		</p>
		<p><?= $this -> message1 ?></p>
		<p>
			<label for='password'>Mot de passe</label>
			<input type="password" name="password" id="password">
		</p>
		<p><?= $this -> message2 ?></p>
		<button>Se connecter</button>
	</form>
	<li><a href="newUser">Créer un compte</a></li>
</main>
